### ISSUE TITLE
One command to retrigger regardless of state

### ISSUE THREAD

**Issue by ulzha** [spotify/styx#177]
It seems we have forced annoying guesswork onto users, by providing `styx trigger` (which works if the workflow instance is inactive) and `styx retry` (which works if the workflow instance is active). Users tend to try both and see whichever works - or they would need to be aware of the workflow instance state to know which variant will work.

I suggest that `retry` should go away or just be an alias of `trigger`, they should work in all cases, except when the workflow is disabled or the instance is already _running_, and in those cases they should provide feedback and perhaps an option to use force...

**Comment by honnix** [comment]
I think they work regardless disabled or not, by design. Already `running` we should check for sure.

**Comment by ulzha** [comment]
One more thing - feedback-wise I was quite confused that the effect of `retry` isn't prominent in `styx events`, like `trigger` is ("triggerExecution          Trigger id: ad-hoc-cli-..."). The system is hiding the manual invention.

**Comment by honnix** [comment]
Agree. A little bit tricky to fix though. `retry` is nothing but a normal `dequeue` event to kick the instance out of waiting state.

**Comment by ulzha** [comment]
Also apparently the retry command talks directly to the scheduler, unlike the other commands that talk to styx-api. So many astonishing differences.

**Comment by honnix** [comment]
`retry` should still be going through styx-api which acts as a proxy in this case.

**Comment by honnix** [comment]
Close to sync with our internal backlog.
