### ISSUE TITLE
styx doc: permission denied

### ISSUE THREAD

**Issue by plumps** [spotify/styx#213]
Hi, 

I am on Nixpkgs (master) on macOS and executing `styx doc` after generating the example data, leads to

`/Users/plumps/.nix-profile/bin/styx: line 252: /nix/store/prr875wd0966mm220ykgsqh15ymqldil-styx-0.6.0/share/doc/styx/index.html: Permission denied`

**Comment by honnix** [comment]
@plumps Hi, thanks for reporting issue! To the best of my knowledge, there is no `styx doc` command. Are you sure this is the `styx` you are after? ;)

**Comment by bergman** [comment]
This seems to relate to https://github.com/styx-static/styx. Closing.
