### ISSUE TITLE
DatastoreExceptions are not handled

### ISSUE THREAD

**Issue by danielnorberg** [spotify/styx#355]
The `Storage` and `DatastoreStorage` interfaces declared `throws IOException` but if there is a datastore error `DatastoreException` is thrown. The `DatastoreException` is a runtime exception and is not a `IOException` subclass. Thus all storage call sites that do `catch (IOException e)` will not actually handle datastore exceptions.

E.g. https://github.com/spotify/styx/blob/master/styx-scheduler-service/src/main/java/com/spotify/styx/StyxScheduler.java#L600

**Comment by honnix** [comment]
fixed by #566
