### ISSUE TITLE
Hitting contention limits on Datastore

### ISSUE THREAD

**Issue by fabriziodemaria** [spotify/styx#356]
We observed a few cases of:
`com.google.cloud.datastore.DatastoreException: too much contention on these datastore entities. please try again.`

This happened when storing workflows: `com.spotify.styx.storage.AggregateStorage.storeWorkflow`

This seems to happen when a component contains a high number of workflows and all the workflows in the component are updated in a loop (at a fast rate). This is probably due to the fact that workflows belonging to the same component are currently part of the same entity group, for which write rate limits apply: https://cloud.google.com/datastore/docs/concepts/limits.

NOTE: The retry mechanism currently handles these occurrences with minimum impact.

**Comment by honnix** [comment]
fixed by flattening the structure.
